global:
 scrape_interval: 15s
 scrape_timeout: 10s
 evaluation_interval: 15s
 
 external_labels:
  monitor: 'praxisprojektswarm'
  
rule_files:
  - "alert_rule.yml"
  - "alert_tasks.yml"
  - "prometheus_alerts.yml"
 
 
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'
 
scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: ['prometheus:9090']
    
  - job_name: cadvisor
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080
      
  - job_name: node
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  
  - job_name: redis_exporter_targets
    static_configs:
      - targets:      
          - redis://10.10.10.1:6379
          - redis://10.10.10.2:6380
          - redis://10.10.10.3:6381          
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis:9121
        
  - job_name: redis_exporter
    static_configs:
      - targets:
        - redis:9121 
 
  - job_name: 'docker-exporter'
    static_configs:
      - targets:
        - 10.10.10.1:9323
        - 10.10.10.2:9323
        - 10.10.10.3:9323
        
  - job_name: 'nginx_exporter'
    static_configs:
      - targets: 
        - 10.10.10.1:9113
        - 10.10.10.2:9113
        - 10.10.10.3:9113
